### ISSUE TITLE
Centos web panel mod

### ISSUE THREAD

**Issue by tharldvs1** [TheHostingTool/TheHostingTool#147]
I am using centos web panel and would like to get tht to work with it. Us this possible? has anyone made a mod for this?

**Comment by Trax2k** [comment]
I wouldn't use TheHostingTool i believe the projects been abandoned.

**Comment by kmark** [comment]
There is no mod that I know of that works with CentOS Web Panel. With that said as long as the software includes a sufficient API it would be possible to write a custom server for THT that adds at least preliminary support.

Unfortunately the overall public interest in TheHostingTool has diminished greatly and given that circumstance I cannot afford to spend more personal time working on its development. See #144 and #146

**Comment by tharldvs1** [comment]
WOW! Thanks
